"""
RISC-V Simulation Infrastructure Service
Extracted from inspiration repos:
  gem5-custom-instructions, gem5-nvdla, gem5-riscv-ccc,
  qemu, renode, dromajo, ripes, riscv-isa-sim (spike),
  riscv-dv, riscv-arch-test, riscv-tests, cvw, tinyfive

Provides a unified interface for:
- Defining custom instructions for gem5 simulation
- Configuring simulation targets (qemu, spike, renode, gem5)
- Managing instruction behaviors and functional units
- Running architecture tests
- Generating test programs (riscv-dv patterns)
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any
from enum import Enum
import json
import os


class SimBackend(Enum):
    """Simulation backends extracted from inspiration repos."""
    GEM5 = "gem5"
    QEMU = "qemu"
    SPIKE = "spike"          # riscv-isa-sim
    RENODE = "renode"
    DROMAJO = "dromajo"
    RIPES = "ripes"
    TINYFIVE = "tinyfive"


class FunctionalUnit(Enum):
    """gem5 functional unit types."""
    INT_ALU = "IntAlu"
    INT_MULT = "IntMult"
    FLOAT_ADD = "FloatAdd"
    FLOAT_CMP = "FloatCmp"
    FLOAT_MULT = "FloatMult"
    FLOAT_DIV = "FloatDiv"
    MEMORY = "Mem"
    VECTOR = "Vector"
    CUSTOM = "Custom"


@dataclass
class CustomInstructionDef:
    """Custom instruction definition for gem5.
    Extracted from gem5-custom-instructions instructions.yaml schema.
    """
    name: str
    description: str
    opclass: str                # Functional unit class name
    latency: int = 1            # Cycles
    pipelined: bool = True      # Can overlap with previous instruction
    fu_count: int = 1           # How many can be in flight
    encoding: str = ""          # Binary encoding pattern
    format: str = "R"           # R, I, S, B, U, J
    behavior_file: str = ""     # Path to behaviors/<name>.cc


@dataclass
class SimConfig:
    """Configuration for a simulation run."""
    backend: SimBackend
    arch: str = "rv64gc"
    abi: str = "lp64d"
    extensions: List[str] = field(default_factory=list)
    memory_size: str = "256M"
    cpu_type: str = "O3CPU"     # gem5: AtomicSimpleCPU, O3CPU, etc.
    clock: str = "1GHz"
    l1_cache: bool = True
    custom_instructions: List[CustomInstructionDef] = field(default_factory=list)
    extra_flags: Dict[str, str] = field(default_factory=dict)


@dataclass
class ArchTestResult:
    """Result of running an architecture test (riscv-arch-test)."""
    test_name: str
    passed: bool
    backend: SimBackend
    duration_ms: float = 0.0
    error_message: str = ""
    coverage: float = 0.0       # Instruction coverage percentage


class SimulationManager:
    """
    Manages RISC-V simulation across multiple backends.
    Extracted patterns from qemu, gem5, spike, renode, dromajo, ripes.
    """

    BACKEND_COMMANDS = {
        SimBackend.QEMU: "qemu-system-riscv64",
        SimBackend.SPIKE: "spike",
        SimBackend.RENODE: "renode",
        SimBackend.DROMAJO: "dromajo",
        SimBackend.GEM5: "gem5.opt",
    }

    BACKEND_FLAGS = {
        SimBackend.QEMU: {
            "machine": "-machine virt",
            "cpu": "-cpu rv64",
            "bios": "-bios default",
            "nographic": "-nographic",
            "memory": "-m {memory_size}",
        },
        SimBackend.SPIKE: {
            "memory": "-m{memory_size}",
            "extensions": "--extension={ext}",
        },
        SimBackend.GEM5: {
            "cpu_type": "--cpu-type={cpu_type}",
            "clock": "--cpu-clock={clock}",
            "l1_cache": "--l1cache" if True else "",
        },
    }

    def __init__(self, config: SimConfig):
        self.config = config
        self.test_results: List[ArchTestResult] = []

    def generate_gem5_custom_inst_yaml(self) -> str:
        """Generate instructions.yaml for gem5-custom-instructions tool.
        Extracted from the instructions.yaml schema.
        """
        lines = [
            "schema_version: 2",
            "# Auto-generated by RISC-V_Injection simulation service",
            "",
        ]
        for inst in self.config.custom_instructions:
            lines.append(f"- name: {inst.name}")
            lines.append(f"  description: \"{inst.description}\"")
            lines.append(f"  opclass: {inst.opclass}")
            lines.append(f"  latency: {inst.latency}")
            lines.append(f"  pipelined: {str(inst.pipelined).lower()}")
            lines.append(f"  fu_count: {inst.fu_count}")
            lines.append(f"  encoding: \"{inst.encoding}\"")
            lines.append(f"  format: {inst.format}")
            lines.append("")

        return "\n".join(lines)

    def generate_behavior_template(self, inst: CustomInstructionDef) -> str:
        """Generate a C++ behavior template for a custom instruction.
        Extracted from gem5-custom-instructions behaviors/ pattern.
        """
        return f"""// Auto-generated behavior for {inst.name}
// {inst.description}
// Functional unit: {inst.opclass}, latency: {inst.latency} cycles

#include "custom_inst.hh"

/**
 * {inst.name} — {inst.description}
 *
 * Encoding: {inst.encoding} ({inst.format}-type)
 * Latency: {inst.latency} cycles, pipelined: {inst.pipelined}
 */
Fault
{inst.name}::execute(ThreadContext *tc, const LegSema &sema)
{{
    // TODO: Implement the actual instruction behavior
    //
    // Access operands via sema:
    //   sema.getReg<RV64_X0>()  — source register
    //   sema.getReg<RV64_X0>(rd) — destination register
    //
    // Return NoFault on success, or a specific fault type.

    auto rs1 = sema.rs1<int64_t>();
    auto rs2 = sema.rs2<int64_t>();
    int64_t result = 0;  // Replace with actual computation

    sema.setReg(rd, result);
    return NoFault;
}}
"""

    def generate_qemu_command(self) -> str:
        """Generate QEMU launch command."""
        flags = self.BACKEND_FLAGS[SimBackend.QEMU]
        cmd = self.BACKEND_COMMANDS[SimBackend.QEMU]
        cmd += " " + flags["machine"]
        cmd += " " + flags["cpu"].format(arch=self.config.arch)
        cmd += " " + flags["nographic"]
        cmd += " " + flags["memory"].format(memory_size=self.config.memory_size)
        if self.config.extensions:
            for ext in self.config.extensions:
                cmd += f" -cpu rv64,{ext}=true"
        for k, v in self.config.extra_flags.items():
            cmd += f" {v}"
        return cmd

    def generate_spike_command(self) -> str:
        """Generate Spike (riscv-isa-sim) launch command."""
        cmd = self.BACKEND_COMMANDS[SimBackend.SPIKE]
        cmd += f" --isa={self.config.arch}"
        cmd += f" -m{self.config.memory_size}"
        for ext in self.config.extensions:
            cmd += f" --extension={ext}"
        return cmd

    def generate_renode_script(self) -> str:
        """Generate a Renode script."""
        return f"""# Auto-generated Renode script for {self.config.arch}
# Extracted from renode inspiration repo patterns

mach create
machine LoadPlatform @platforms/cpus/riscv_virt.repl

# Set up memory
sysbus set_ram_size {self.config.memory_size}

# Load firmware/binary
# Replace with your binary path:
# sysbus LoadBinary @path/to/firmware.elf

# Start execution
cpu SetActivationMode Halt
showAnalyzer
start
"""

    def generate_dromajo_config(self) -> str:
        """Generate Dromajo configuration."""
        return f"""# Auto-generated Dromajo config
# Extracted from dromajo inspiration repo patterns

[main]
model = {self.config.arch}
memory = {self.config.memory_size}
bootrom = default

[cpu]
cores = 1
extensions = {','.join(self.config.extensions)}
"""

    def run_arch_test(
        self, test_name: str, backend: Optional[SimBackend] = None
    ) -> ArchTestResult:
        """Run an architecture test (riscv-arch-test pattern).
        In production, this would invoke the actual test runner.
        """
        b = backend or self.config.backend
        result = ArchTestResult(
            test_name=test_name,
            passed=True,
            backend=b,
        )
        self.test_results.append(result)
        return result

    def get_test_summary(self) -> Dict[str, Any]:
        """Get summary of all test results."""
        total = len(self.test_results)
        passed = sum(1 for r in self.test_results if r.passed)
        failed = total - passed
        avg_coverage = (
            sum(r.coverage for r in self.test_results) / total if total > 0 else 0
        )
        return {
            "total": total,
            "passed": passed,
            "failed": failed,
            "pass_rate": (passed / total * 100) if total > 0 else 0,
            "avg_coverage": avg_coverage,
            "by_backend": {
                b.value: {
                    "total": sum(1 for r in self.test_results if r.backend == b),
                    "passed": sum(1 for r in self.test_results if r.backend == b and r.passed),
                }
                for b in SimBackend
                if any(r.backend == b for r in self.test_results)
            },
        }


class TestProgramGenerator:
    """
    Generates random test programs for RISC-V.
    Extracted from riscv-dv inspiration repo patterns.
    """

    def __init__(self, arch: str = "rv64gc"):
        self.arch = arch
        self.seed = 42

    def generate_pseudo_test(
        self,
        num_instructions: int = 100,
        categories: Optional[List[str]] = None,
    ) -> str:
        """Generate a pseudo-random test program.

        Args:
            num_instructions: Number of instructions to generate.
            categories: Instruction categories to include (e.g. ["arith", "branch", "mem"]).

        Returns:
            RISC-V assembly text.
        """
        if categories is None:
            categories = ["arith", "logic", "branch", "memory"]

        import random
        rng = random.Random(self.seed)

        arith_ops = ["add", "sub", "mul", "div", "rem", "addi"]
        logic_ops = ["and", "or", "xor", "sll", "srl", "sra", "andi", "ori", "xori"]
        branch_ops = ["beq", "bne", "blt", "bge", "jal", "jalr"]
        memory_ops = ["lw", "sw", "lb", "sb", "lh", "sh", "ld", "sd"]

        lines = [
            f"# Auto-generated test program for {self.arch}",
            f"# Seed: {self.seed}, {num_instructions} instructions",
            "",
            ".text",
            ".globl _start",
            "_start:",
        ]

        for i in range(num_instructions):
            cat = rng.choice(categories)
            if cat == "arith":
                op = rng.choice(arith_ops)
                rd = rng.randint(1, 31)
                rs1 = rng.randint(1, 31)
                if op.endswith("i"):
                    imm = rng.randint(-2048, 2047)
                    lines.append(f"  {op} x{rd}, x{rs1}, {imm}")
                else:
                    rs2 = rng.randint(1, 31)
                    lines.append(f"  {op} x{rd}, x{rs1}, x{rs2}")
            elif cat == "logic":
                op = rng.choice(logic_ops)
                rd = rng.randint(1, 31)
                rs1 = rng.randint(1, 31)
                if op.endswith("i"):
                    imm = rng.randint(-2048, 2047)
                    lines.append(f"  {op} x{rd}, x{rs1}, {imm}")
                else:
                    rs2 = rng.randint(1, 31)
                    lines.append(f"  {op} x{rd}, x{rs1}, x{rs2}")
            elif cat == "branch":
                op = rng.choice(branch_ops)
                rs1 = rng.randint(1, 31)
                rs2 = rng.randint(1, 31)
                offset = rng.randint(-128, 127)
                if op in ("jal", "jalr"):
                    rd = rng.randint(1, 31)
                    lines.append(f"  {op} x{rd}, {offset}")
                else:
                    lines.append(f"  {op} x{rs1}, x{rs2}, {offset}")
            elif cat == "memory":
                op = rng.choice(memory_ops)
                rs1 = rng.randint(1, 31)
                rs2 = rng.randint(1, 31)
                offset = rng.randint(-256, 255)
                lines.append(f"  {op} x{rs2}, {offset}(x{rs1})")

        lines.append("")
        lines.append("  j .")
        return "\n".join(lines)
